/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Procedimiento;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estudiante;

/**
 *
 * @author rodrigo
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        
        
        
        jtxt_rut.setEnabled(false);
        jtxt_id.setEnabled(false);
    }

       
       
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrb_buscar_por_rut = new javax.swing.JRadioButton();
        jrb_buscar_por_id = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_datos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_sede = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_pago_mensualidad = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbl_pago_matricula = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtxt_rut = new javax.swing.JTextField();
        jtxt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtn_buscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/rodrigo/Documents/DUOCUC2021/2DO SEMESTRE/DISEÑO DE SOFTWARE DE ESCRITORIO/EJERCICIOS JAVA/BD_Proyecto/src/vista/logo2.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Buscar Estudiante");

        buttonGroup1.add(jrb_buscar_por_rut);
        jrb_buscar_por_rut.setText("Buscar por RUT");
        jrb_buscar_por_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_buscar_por_rutActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb_buscar_por_id);
        jrb_buscar_por_id.setText("Buscar por ID");
        jrb_buscar_por_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_buscar_por_idActionPerformed(evt);
            }
        });

        jtbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "RUT", "Nombre", "Appellido Paterno", "Apellido Materno", "Edad", "NEM", "Gratuidad"
            }
        ));
        jScrollPane1.setViewportView(jtbl_datos);
        if (jtbl_datos.getColumnModel().getColumnCount() > 0) {
            jtbl_datos.getColumnModel().getColumn(0).setPreferredWidth(20);
            jtbl_datos.getColumnModel().getColumn(1).setPreferredWidth(60);
            jtbl_datos.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtbl_datos.getColumnModel().getColumn(3).setPreferredWidth(110);
            jtbl_datos.getColumnModel().getColumn(4).setPreferredWidth(120);
            jtbl_datos.getColumnModel().getColumn(5).setPreferredWidth(2);
            jtbl_datos.getColumnModel().getColumn(6).setPreferredWidth(10);
            jtbl_datos.getColumnModel().getColumn(7).setPreferredWidth(20);
        }

        jtbl_sede.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sede", "Nombre Carrera"
            }
        ));
        jScrollPane2.setViewportView(jtbl_sede);
        if (jtbl_sede.getColumnModel().getColumnCount() > 0) {
            jtbl_sede.getColumnModel().getColumn(0).setPreferredWidth(90);
            jtbl_sede.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        jtbl_pago_mensualidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Valor Mensualidad", "Estado Mensualidad", "Forma Pago Mensualidad", "Fecha de pago"
            }
        ));
        jScrollPane3.setViewportView(jtbl_pago_mensualidad);
        if (jtbl_pago_mensualidad.getColumnModel().getColumnCount() > 0) {
            jtbl_pago_mensualidad.getColumnModel().getColumn(0).setPreferredWidth(90);
            jtbl_pago_mensualidad.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbl_pago_mensualidad.getColumnModel().getColumn(2).setPreferredWidth(120);
            jtbl_pago_mensualidad.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jtbl_pago_matricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Valor Matricula", "Estado Matricula", "Forma Pago Matricula", "Fecha de Pago"
            }
        ));
        jScrollPane4.setViewportView(jtbl_pago_matricula);
        if (jtbl_pago_matricula.getColumnModel().getColumnCount() > 0) {
            jtbl_pago_matricula.getColumnModel().getColumn(0).setPreferredWidth(90);
            jtbl_pago_matricula.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbl_pago_matricula.getColumnModel().getColumn(2).setPreferredWidth(120);
            jtbl_pago_matricula.getColumnModel().getColumn(3).setPreferredWidth(110);
            jtbl_pago_matricula.getColumnModel().getColumn(3).setHeaderValue("Estado mensualidad");
        }

        jLabel3.setText("Ingrese RUT");

        jtxt_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_rutActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese ID");

        jbtn_buscar.setIcon(new javax.swing.ImageIcon("/Users/rodrigo/Documents/DUOCUC2021/2DO SEMESTRE/DISEÑO DE SOFTWARE DE ESCRITORIO/EJERCICIOS JAVA/BD_Proyecto/src/icons8-búsqueda-de-propiedad-48.png")); // NOI18N
        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("/Users/rodrigo/Documents/DUOCUC2021/2DO SEMESTRE/DISEÑO DE SOFTWARE DE ESCRITORIO/EJERCICIOS JAVA/BD_Proyecto/src/volver (2).png")); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(341, 341, 341)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jrb_buscar_por_rut)
                                        .addGap(54, 54, 54))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jbtn_buscar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addComponent(jrb_buscar_por_id))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jrb_buscar_por_rut)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jrb_buscar_por_id)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jtxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(23, 23, 23)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_buscar_por_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_buscar_por_rutActionPerformed
        
        if (this.jrb_buscar_por_rut.isSelected()){
            jtxt_rut.setEnabled(true);
             jtxt_id.setEnabled(false);
        }



// TODO add your handling code here:
    }//GEN-LAST:event_jrb_buscar_por_rutActionPerformed

    private void jtxt_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_rutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_rutActionPerformed

    private void jrb_buscar_por_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_buscar_por_idActionPerformed
       if (this.jrb_buscar_por_id.isSelected()){
            jtxt_id.setEnabled(true);
            jtxt_rut.setEnabled(false);
        
       }

// TODO add your handling code here:
    }//GEN-LAST:event_jrb_buscar_por_idActionPerformed

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        String rut;
         
        rut = this.jtxt_rut.getText();
        if (rut.isEmpty()){

         
            JOptionPane.showMessageDialog(this, "El RUT no puede estar vacío", "Validación", 1);
            this.jtxt_rut.requestFocus();
            return;
        } else {  
         String nombre, appaterno, apmaterno, gratuidad;
         int edad, id;
         double nem;

        Procedimiento proce = new Procedimiento();
        DefaultTableModel tablaDato = (DefaultTableModel) this.jtbl_datos.getModel();
        DefaultTableModel tablaSede = (DefaultTableModel) this.jtbl_sede.getModel();
        DefaultTableModel tablaMatricula = (DefaultTableModel) this.jtbl_pago_matricula.getModel();
        DefaultTableModel tablaMensualidad = (DefaultTableModel) this.jtbl_pago_mensualidad.getModel();
 
        rut = this.jtxt_rut.getText();

         tablaDato.setRowCount(0);

         boolean flag;
           // Procedimiento proce = new Procedimiento();
            proce.buscarEstudiantePorRut(rut);
            flag = proce.buscarEstudiantePorRut(rut);
            if (flag == true) {
              Estudiante estudiante = new Estudiante();  
             rut = estudiante.getRut();
             nombre = estudiante.getNombre();
             apmaterno = estudiante.getApmaterno();
             appaterno = estudiante.getAppaterno();
                     gratuidad = estudiante.getGratuidad();
                    
                     edad = estudiante.getEdad();
                     
                     id = estudiante.getId();
                     nem = estudiante.getNem();
                     
               tablaDato.addRow(new Object[]{rut, nombre, apmaterno, appaterno, gratuidad, edad, id, nem});
//                     

            }
        }

////             id = libro.getIdLibro();
////            titulo = libro.getTitulo();
////            autor = libro.getAutor();
////            precio = libro.getPrecio();
////            disponible = libro.isDisponible();
////            
////            modelo.addRow(new Object[]{id, titulo, autor, precio, disponible});   
//                
//                
//            }
//        
//        
//         }
//        
//        
//        
//        
//        
//        
//        
//        
//        
////        
//////        if 
////            Libro libro = reg.buscarPorId(id);
////            id = libro.getIdLibro();
////            titulo = libro.getTitulo();
////            autor = libro.getAutor();
////            precio = libro.getPrecio();
////            disponible = libro.isDisponible();
////            
////            modelo.addRow(new Object[]{id, titulo, autor, precio, disponible});
//
//
//
//
//
//
//
//
////               (id == 0) {//listar todos
//////            List<Libro> lista = reg.buscarTodos();
////            for (Libro libro : lista) {
////                id = libro.getIdLibro();
////                titulo = libro.getTitulo();
////                autor = libro.getAutor();
////                precio = libro.getPrecio();
////                disponible = libro.isDisponible();
////
////                modelo.addRow(new Object[]{id, titulo, autor, precio, disponible});
////            }
//
////        } else { //listar por id
////
////            Libro libro = reg.buscarPorId(id);
////            id = libro.getIdLibro();
////            titulo = libro.getTitulo();
////            autor = libro.getAutor();
////            precio = libro.getPrecio();
////            disponible = libro.isDisponible();
////            
////            modelo.addRow(new Object[]{id, titulo, autor, precio, disponible});
////        }
////            
////            
//            
//            
//            
//            
//            
//            
//            
//        }
//
//
//
//
//
//



        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JRadioButton jrb_buscar_por_id;
    private javax.swing.JRadioButton jrb_buscar_por_rut;
    private javax.swing.JTable jtbl_datos;
    private javax.swing.JTable jtbl_pago_matricula;
    private javax.swing.JTable jtbl_pago_mensualidad;
    private javax.swing.JTable jtbl_sede;
    private javax.swing.JTextField jtxt_id;
    private javax.swing.JTextField jtxt_rut;
    // End of variables declaration//GEN-END:variables
}
