/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Procedimiento;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estudiante;

/**
 *
 * @author rodrigo
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();

        jtxt_rut.setEnabled(false);
        jtxt_id.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_sede = new javax.swing.JTable();
        jbtn_limpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbl_pago_matricula = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_rut = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtxt_id = new javax.swing.JTextField();
        jrb_buscar_por_rut = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jrb_buscar_por_id = new javax.swing.JRadioButton();
        jbtn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_datos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbl_sede = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtbl_sede.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sede", "Nombre Carrera"
            }
        ));
        jtbl_sede.getTableHeader().setResizingAllowed(false);
        jtbl_sede.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtbl_sede);
        if (jtbl_sede.getColumnModel().getColumnCount() > 0) {
            jtbl_sede.getColumnModel().getColumn(0).setPreferredWidth(90);
            jtbl_sede.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 587, 56));

        jbtn_limpiar.setBackground(new java.awt.Color(51, 51, 51));
        jbtn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/limpieza-de-datos.png"))); // NOI18N
        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 724, 9));

        jtbl_pago_matricula = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtbl_pago_matricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor Matricula", "Estado Matricula", "Fecha de Pago", "Valor Pagado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_pago_matricula.getTableHeader().setResizingAllowed(false);
        jtbl_pago_matricula.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtbl_pago_matricula);
        if (jtbl_pago_matricula.getColumnModel().getColumnCount() > 0) {
            jtbl_pago_matricula.getColumnModel().getColumn(0).setPreferredWidth(90);
            jtbl_pago_matricula.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbl_pago_matricula.getColumnModel().getColumn(2).setPreferredWidth(110);
            jtbl_pago_matricula.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 701, 57));

        jLabel5.setBackground(new java.awt.Color(255, 204, 0));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("SEDE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 204, 0));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("DATOS PERSONALES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese RUT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 204, 0));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("MATRÍCULA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/logo2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, 44));

        jtxt_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_rutActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 119, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 724, 9));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buscar Estudiante");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));
        jPanel1.add(jtxt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 95, -1));

        buttonGroup1.add(jrb_buscar_por_rut);
        jrb_buscar_por_rut.setForeground(new java.awt.Color(0, 0, 0));
        jrb_buscar_por_rut.setText("Buscar por RUT");
        jrb_buscar_por_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_buscar_por_rutActionPerformed(evt);
            }
        });
        jPanel1.add(jrb_buscar_por_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingrese ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        buttonGroup1.add(jrb_buscar_por_id);
        jrb_buscar_por_id.setForeground(new java.awt.Color(0, 0, 0));
        jrb_buscar_por_id.setText("Buscar por ID");
        jrb_buscar_por_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_buscar_por_idActionPerformed(evt);
            }
        });
        jPanel1.add(jrb_buscar_por_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jbtn_buscar.setBackground(new java.awt.Color(51, 51, 51));
        jbtn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icons8-búsqueda-de-propiedad-48.png"))); // NOI18N
        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, 44));

        jtbl_datos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RUT", "Nombre", "Appellido Paterno", "Apellido Materno", "Edad", "NEM", "Gratuidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_datos.getTableHeader().setResizingAllowed(false);
        jtbl_datos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbl_datos);
        if (jtbl_datos.getColumnModel().getColumnCount() > 0) {
            jtbl_datos.getColumnModel().getColumn(0).setPreferredWidth(20);
            jtbl_datos.getColumnModel().getColumn(5).setPreferredWidth(20);
            jtbl_datos.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 903, 58));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/volver (2).png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, 44));

        jSeparator1.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 818, 12));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_buscar_por_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_buscar_por_rutActionPerformed

        if (this.jrb_buscar_por_rut.isSelected()) {
            jtxt_rut.setEnabled(true);
            jtxt_id.setEnabled(false);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jrb_buscar_por_rutActionPerformed

    private void jtxt_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_rutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_rutActionPerformed

    private void jrb_buscar_por_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_buscar_por_idActionPerformed
        if (this.jrb_buscar_por_id.isSelected()) {
            jtxt_id.setEnabled(true);
            jtxt_rut.setEnabled(false);

        }

// TODO add your handling code here:
    }//GEN-LAST:event_jrb_buscar_por_idActionPerformed

    //private void 
    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        if (this.jrb_buscar_por_rut.isSelected()) {
            String rut;
            rut = this.jtxt_rut.getText();

            if (rut.isEmpty()) {

                JOptionPane.showMessageDialog(this, "El RUT no puede estar vacío", "Validación", 1);
                this.jtxt_rut.requestFocus();
                return;
            } else {

                //si el estudiante no existe
                boolean flag;
                Procedimiento proce = new Procedimiento();
                proce.buscarEstudiantePorRut(rut);
                flag = proce.buscarEstudiantePorRutBandera(rut);
                if (flag == false) {
                    JOptionPane.showMessageDialog(this, "El estudiante no existe en la base de datos", "Validación", 1);
                    this.jtxt_rut.setText("");
                    this.jtxt_rut.requestFocus();
                } //si el estudiante exixte
                else {
                    String nombre, appaterno, apmaterno, gratuidad, estado_matricula, nombre_carrera, nombre_sede;
                    int edad, id, valor_matricula, valor_matricula_pagar;
                    double nem;
                    Date fecha_pago_matricula;

                    // Procedimiento proce = new Procedimiento();
                    DefaultTableModel tablaDatos = (DefaultTableModel) this.jtbl_datos.getModel();
                    DefaultTableModel tablaSede = (DefaultTableModel) this.jtbl_sede.getModel();
                    DefaultTableModel tablaMatricula = (DefaultTableModel) this.jtbl_pago_matricula.getModel();

                    //Objeto
                    Estudiante estudiante = proce.buscarEstudiantePorRut(rut);

                    id = estudiante.getId();
                    rut = estudiante.getRut();
                    nombre = estudiante.getNombre();

                    appaterno = estudiante.getAppaterno();
                    apmaterno = estudiante.getApmaterno();
                    edad = estudiante.getEdad();
                    nem = estudiante.getNem();
                    gratuidad = estudiante.getGratuidad();

                    //Datos obtenidos de la base de datos se agregan a tabla1
                    tablaDatos.addRow(new Object[]{id, rut, nombre, appaterno, apmaterno, edad, nem, gratuidad});

                    nombre_sede = estudiante.getNombre_sede();
                    nombre_carrera = estudiante.getNombre_carrera();
                    //Datos obtenidos de la base de datos se agregan a tabla2
                    tablaSede.addRow(new Object[]{nombre_sede, nombre_carrera});

                    valor_matricula = estudiante.getValor_matricula();
                    estado_matricula = estudiante.getEstado_matricula();
                    fecha_pago_matricula = estudiante.getFecha_pago_matricula();
                    valor_matricula_pagar = estudiante.getValor_matricula_pagar();
                    //Datos obtenidos de la base de datos se agregan a tabla3
                    tablaMatricula.addRow(new Object[]{valor_matricula, estado_matricula, fecha_pago_matricula, valor_matricula_pagar});

                    jbtn_buscar.setEnabled(false);
                    jtxt_rut.setText("");
                }
            }
        }

        if (this.jrb_buscar_por_id.isSelected()) {

            int id;

            try {
                id = Integer.parseInt(this.jtxt_id.getText());

            } catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(this, "El id debe ser un numero", "Validación", 1);
                this.jtxt_id.setText("");
                this.jtxt_id.requestFocus();
                return;
            }

            //si el estudiante no existe
            boolean flag;
            Procedimiento proce = new Procedimiento();
            proce.buscarEstudiantePorId(id);
            flag = proce.buscarEstudiantePorIdBandera(id);
            if (flag == false) {
                JOptionPane.showMessageDialog(this, "El estudiante no existe en la base de datos", "Validación", 1);
                this.jtxt_id.setText("");
                this.jtxt_id.requestFocus();
            } //si el estudiante exixte
            else {
                String rut, nombre, appaterno, apmaterno, gratuidad, estado_matricula, nombre_carrera, nombre_sede;
                int edad, valor_matricula, valor_matricula_pagar;
                double nem;
                Date fecha_pago_matricula;

                Procedimiento proce2 = new Procedimiento();
                DefaultTableModel tablaDatos = (DefaultTableModel) this.jtbl_datos.getModel();
                DefaultTableModel tablaSede = (DefaultTableModel) this.jtbl_sede.getModel();
                DefaultTableModel tablaMatricula = (DefaultTableModel) this.jtbl_pago_matricula.getModel();

                //Objeto
                Estudiante estudiante = proce2.buscarEstudiantePorId(id);

                id = estudiante.getId();
                rut = estudiante.getRut();
                nombre = estudiante.getNombre();

                appaterno = estudiante.getAppaterno();
                apmaterno = estudiante.getApmaterno();
                edad = estudiante.getEdad();
                nem = estudiante.getNem();
                gratuidad = estudiante.getGratuidad();

                //Datos obtenidos de la base de datos se agregan a tabla1
                tablaDatos.addRow(new Object[]{id, rut, nombre, appaterno, apmaterno, edad, nem, gratuidad});

                nombre_sede = estudiante.getNombre_sede();
                nombre_carrera = estudiante.getNombre_carrera();
                //Datos obtenidos de la base de datos se agregan a tabla2
                tablaSede.addRow(new Object[]{nombre_sede, nombre_carrera});

                valor_matricula = estudiante.getValor_matricula();
                estado_matricula = estudiante.getEstado_matricula();
                fecha_pago_matricula = estudiante.getFecha_pago_matricula();
                valor_matricula_pagar = estudiante.getValor_matricula_pagar();
                //Datos obtenidos de la base de datos se agregan a tabla3
                tablaMatricula.addRow(new Object[]{valor_matricula, estado_matricula, fecha_pago_matricula, valor_matricula_pagar});

                jbtn_buscar.setEnabled(false);
                jtxt_id.setText("");

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    //Limpia la tala 1
    public void limpiarTablaDatos() {
        DefaultTableModel temp = (DefaultTableModel) jtbl_datos.getModel();
        int filas = jtbl_datos.getRowCount();

        for (int a = 0; filas > a; a++) {
            temp.removeRow(0);
        }
    }

    //Limpia la tala 2
    public void limpiarTablaSede() {
        DefaultTableModel temp2 = (DefaultTableModel) jtbl_sede.getModel();
        int filas2 = jtbl_sede.getRowCount();

        for (int a = 0; filas2 > a; a++) {
            temp2.removeRow(0);
        }
    }

    //Limpia la tala 3
    public void limpiarTablaPagoMatricula() {
        DefaultTableModel temp3 = (DefaultTableModel) jtbl_pago_matricula.getModel();
        int filas3 = jtbl_pago_matricula.getRowCount();

        for (int a = 0; filas3 > a; a++) {
            temp3.removeRow(0);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed

        this.jtxt_rut.setText("");
        this.jtxt_id.setText("");

        limpiarTablaDatos();
        limpiarTablaSede();
        limpiarTablaPagoMatricula();

        jbtn_buscar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Buscar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JRadioButton jrb_buscar_por_id;
    private javax.swing.JRadioButton jrb_buscar_por_rut;
    private javax.swing.JTable jtbl_datos;
    private javax.swing.JTable jtbl_pago_matricula;
    private javax.swing.JTable jtbl_sede;
    private javax.swing.JTextField jtxt_id;
    private javax.swing.JTextField jtxt_rut;
    // End of variables declaration//GEN-END:variables
}
