package vista;

import controlador.Procedimiento;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estudiante;

/**
 *
 * @author navar rodrigo Vazques Franco Navarrete Cristian Ubilla..
 */
public class Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_idbuscar = new javax.swing.JTextField();
        jbtn_Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Datos = new javax.swing.JTable();
        jtbn_Eliminar = new javax.swing.JButton();
        jtbn_volver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbtn_rut = new javax.swing.JRadioButton();
        jbtn_id = new javax.swing.JRadioButton();
        jtxt_rut = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("                 Eliminar Datos");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/descargalogoduoc.png"))); // NOI18N

        jtxt_idbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idbuscarActionPerformed(evt);
            }
        });

        jbtn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/buscar.png"))); // NOI18N
        jbtn_Buscar.setText("Buscar");
        jbtn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_BuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese ID :");

        jTbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "RUT", "Nombre", "Apellido paterno", "Apellido materno", "Nem", "Gratuidad", "Edad", "Nombre carrera", "Nombre Sede", "Estado Matricula", "Valor Matricula", "Fecha pago matricula", "Valor_matricula_pagar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbl_Datos);
        if (jTbl_Datos.getColumnModel().getColumnCount() > 0) {
            jTbl_Datos.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTbl_Datos.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTbl_Datos.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTbl_Datos.getColumnModel().getColumn(3).setPreferredWidth(300);
            jTbl_Datos.getColumnModel().getColumn(4).setPreferredWidth(300);
            jTbl_Datos.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTbl_Datos.getColumnModel().getColumn(6).setPreferredWidth(300);
            jTbl_Datos.getColumnModel().getColumn(7).setPreferredWidth(150);
            jTbl_Datos.getColumnModel().getColumn(8).setPreferredWidth(300);
            jTbl_Datos.getColumnModel().getColumn(9).setPreferredWidth(300);
            jTbl_Datos.getColumnModel().getColumn(10).setPreferredWidth(200);
            jTbl_Datos.getColumnModel().getColumn(11).setPreferredWidth(150);
            jTbl_Datos.getColumnModel().getColumn(12).setPreferredWidth(200);
            jTbl_Datos.getColumnModel().getColumn(13).setPreferredWidth(300);
        }

        jtbn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/boton-eliminar.png"))); // NOI18N
        jtbn_Eliminar.setText("Eliminar");
        jtbn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbn_EliminarActionPerformed(evt);
            }
        });

        jtbn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/logout.png"))); // NOI18N
        jtbn_volver.setText("Volver");
        jtbn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbn_volverActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese Rut:");

        jbtn_rut.setText("Rut");

        jbtn_id.setText("ID");
        jbtn_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtn_id)
                        .addGap(201, 201, 201)
                        .addComponent(jbtn_rut))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jtbn_volver)
                        .addGap(301, 301, 301)
                        .addComponent(jtbn_Eliminar)
                        .addGap(175, 175, 175))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_idbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_Buscar)))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_idbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Buscar)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_rut)
                    .addComponent(jbtn_id))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbn_Eliminar)
                    .addComponent(jtbn_volver)))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn_EliminarActionPerformed
        if (this.jbtn_rut.isSelected()) {

            this.jtxt_idbuscar.setEnabled(false);
            String rut;

            rut = this.jtxt_rut.getText();

            Procedimiento proce = new Procedimiento();

            int opcion = JOptionPane.showConfirmDialog(this, "Seguro que deseas eliminar al estudiandte?", "Eliminar", 0);

            if (opcion == 0) {
                proce.eliminarEstudiantePorRut(rut);
                JOptionPane.showMessageDialog(this, "Estudiante Eliminado", "Eliminar", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Estudiante no Eliminado", "Eliminar", 2);
            }
        }
        if (this.jbtn_id.isSelected()) {

            this.jtxt_rut.setEnabled(false);

            int id;
            Procedimiento proce = new Procedimiento();
            id = Integer.parseInt(this.jtxt_idbuscar.getText());

            int opcion = JOptionPane.showConfirmDialog(this, "Seguro que deseas eliminar al estudiandte?", "Eliminar", 0);

            if (opcion == 0) {
                proce.eliminarEstudiante(id);
                JOptionPane.showMessageDialog(this, "Estudiante Eliminado", "Eliminar", 1);
            } else {
                JOptionPane.showMessageDialog(this, "Estudiante no Eliminado", "Eliminar", 2);
            }
    }//GEN-LAST:event_jtbn_EliminarActionPerformed
    }
    private void jbtn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_BuscarActionPerformed

//    jrbtn_rut.setEnabled(false);
//    jrbtn_id.setEnabled(false);
        String nombre, rut, apmaterno, appaterno, gratuidad, nombre_carrera, nombre_sede, estado_matricula;
        int id, edad, valor_matricula;
        double nem;
        Date fecha_pago_matricula;

        Procedimiento proc = new Procedimiento();
        DefaultTableModel modelo = (DefaultTableModel) this.jTbl_Datos.getModel();

        try {
            id = Integer.parseInt(this.jtxt_idbuscar.getText());
        } catch (NumberFormatException e) {
            id = 0;

        }

        modelo.setRowCount(0);

        if (id == 0) {
            List<Estudiante> lista = proc.buscarTodos();
            for (Estudiante estudiante : lista) {
                id = estudiante.getId();
                rut = estudiante.getRut();
                nombre = estudiante.getNombre();
                appaterno = estudiante.getAppaterno();
                apmaterno = estudiante.getApmaterno();
                nem = estudiante.getNem();
                gratuidad = estudiante.getGratuidad();
                edad = estudiante.getEdad();
                nombre_carrera = estudiante.getNombre_carrera();
                nombre_sede = estudiante.getNombre_sede();
                estado_matricula = estudiante.getEstado_matricula();
                valor_matricula = estudiante.getValor_matricula();
                fecha_pago_matricula = estudiante.getFecha_pago_matricula();

                modelo.addRow(new Object[]{id, rut, nombre, appaterno, apmaterno, nem, gratuidad, edad, nombre_carrera, nombre_sede, estado_matricula, valor_matricula, fecha_pago_matricula});
            }
        } else {
            Estudiante estudiante = proc.buscarEstudiantePorId(id);
            id = estudiante.getId();
            rut = estudiante.getRut();
            nombre = estudiante.getNombre();
            appaterno = estudiante.getAppaterno();
            apmaterno = estudiante.getApmaterno();
            nem = estudiante.getNem();
            gratuidad = estudiante.getGratuidad();
            edad = estudiante.getEdad();
            nombre_carrera = estudiante.getNombre_carrera();
            nombre_sede = estudiante.getNombre_sede();
            estado_matricula = estudiante.getEstado_matricula();
            valor_matricula = estudiante.getValor_matricula();
            fecha_pago_matricula = estudiante.getFecha_pago_matricula();

            modelo.addRow(new Object[]{id, rut, nombre, appaterno, apmaterno, nem, gratuidad, edad, nombre_carrera, nombre_sede, estado_matricula, valor_matricula, fecha_pago_matricula,});
        }


    }//GEN-LAST:event_jbtn_BuscarActionPerformed

    private void jtbn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn_volverActionPerformed
        dispose();
    }//GEN-LAST:event_jtbn_volverActionPerformed

    private void jtxt_idbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idbuscarActionPerformed

    private void jbtn_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_Datos;
    private javax.swing.JButton jbtn_Buscar;
    private javax.swing.JRadioButton jbtn_id;
    private javax.swing.JRadioButton jbtn_rut;
    private javax.swing.JButton jtbn_Eliminar;
    private javax.swing.JButton jtbn_volver;
    private javax.swing.JTextField jtxt_idbuscar;
    private javax.swing.JTextField jtxt_rut;
    // End of variables declaration//GEN-END:variables
}
