/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Procedimiento;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Estudiante;

/**
 *
 * @author rodrigo
 */
public class Listar extends javax.swing.JFrame {

    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_datos_todos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jbtn_mostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar");

        jtbl_datos_todos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "R.U.T.", "Nombre", "Apellido Paterno", "Apellido Materno", "Edad", "N.E.M.", "Gratuidad", "Carrera", "Sede", "Estado Matricula", "Fecha Pago", "Matricula", "Valor Pagado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbl_datos_todos);
        if (jtbl_datos_todos.getColumnModel().getColumnCount() > 0) {
            jtbl_datos_todos.getColumnModel().getColumn(0).setMinWidth(2);
            jtbl_datos_todos.getColumnModel().getColumn(0).setPreferredWidth(3);
            jtbl_datos_todos.getColumnModel().getColumn(1).setPreferredWidth(40);
            jtbl_datos_todos.getColumnModel().getColumn(5).setPreferredWidth(3);
            jtbl_datos_todos.getColumnModel().getColumn(6).setPreferredWidth(10);
            jtbl_datos_todos.getColumnModel().getColumn(7).setPreferredWidth(20);
            jtbl_datos_todos.getColumnModel().getColumn(10).setPreferredWidth(40);
            jtbl_datos_todos.getColumnModel().getColumn(11).setPreferredWidth(25);
            jtbl_datos_todos.getColumnModel().getColumn(12).setPreferredWidth(20);
            jtbl_datos_todos.getColumnModel().getColumn(13).setPreferredWidth(25);
        }

        jSeparator1.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtn_mostrar.setText("Mostrar Base de Datos");
        jbtn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_mostrarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/logo2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Listar todos los Datos.");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/volver (2).png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(418, 418, 418)
                .addComponent(jLabel1)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jbtn_mostrar)
                        .addGap(353, 353, 353)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1471, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_mostrar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_mostrarActionPerformed

        String rut, nombre, appaterno, apmaterno, gratuidad, estado_matricula, nombre_carrera, nombre_sede;
        int edad, id, valor_matricula, valor_matricula_pagar;
        double nem;
        Date fecha_pago_matricula;

        Procedimiento proce = new Procedimiento();

        DefaultTableModel tablaDatosTodos = (DefaultTableModel) this.jtbl_datos_todos.getModel();

        tablaDatosTodos.setRowCount(0);

        List<Estudiante> listaEstudiante = proce.buscarTodos();
        for (Estudiante estudiante : listaEstudiante) {

            id = estudiante.getId();
            rut = estudiante.getRut();
            nombre = estudiante.getNombre();
            appaterno = estudiante.getAppaterno();
            apmaterno = estudiante.getApmaterno();
            edad = estudiante.getEdad();
            nem = estudiante.getNem();
            gratuidad = estudiante.getGratuidad();
            nombre_carrera = estudiante.getNombre_carrera();
            nombre_sede = estudiante.getNombre_sede();
            estado_matricula = estudiante.getEstado_matricula();
            fecha_pago_matricula = estudiante.getFecha_pago_matricula();
            valor_matricula = estudiante.getValor_matricula();
            valor_matricula_pagar = estudiante.getValor_matricula_pagar();

            //Datos obtenidos de la base de datos se agregan a tabla
            tablaDatosTodos.addRow(new Object[]{id, rut, nombre, appaterno, apmaterno, edad, nem, gratuidad, nombre_carrera, nombre_sede, estado_matricula, fecha_pago_matricula, valor_matricula, valor_matricula_pagar});
            // }

        }


    }//GEN-LAST:event_jbtn_mostrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtn_mostrar;
    private javax.swing.JTable jtbl_datos_todos;
    // End of variables declaration//GEN-END:variables
}
